# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.user_locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: ['@session']
        tags:
            - { name: kernel.event_listener, event: security.interactive_login, method: onInteractiveLogin }
    app.twig.unicode_extension:
        class: AppBundle\Twig\UnicodeExtension
        tags:
            - { name: twig.extension }
    app.twig.priceformatter_extension:
        class: AppBundle\Twig\PriceFormatterExtension
        tags:
            - { name: twig.extension }